name: Scheduled Preview Cleanup

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4am UTC every day
  workflow_dispatch:

jobs:
  cleanup-previews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Clean up preview directories
        run: |
          # Remove all preview directories except staging
          if [ -d public/generated ]; then
            find public/generated -maxdepth 1 -type d -name 'sync*' -exec rm -rf {} +
            echo "Preview directories cleaned up."
          else
            echo "No preview directories to clean."
          fi

      - name: Regenerate main index.html
        run: node scripts/generate-docs.v2.js --index-only

      - name: Publish cleanup to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.OPENAPI_CICD_WORKFLOW_TOKEN }}
          publish_dir: public
          destination_dir: .
          user_name: GitHub Actions
          user_email: actions@github.com
          keep_files: true
